export const SET_USER_INFO = "SET_USER_INFO";
export const CLEAR_USER_INFO = "CLEAR_USER_INFO";

export const SET_WELCOME_TOAST_DISPLAY = "SET_WELCOME_TOAST_DISPLAY";

export const ADD_LOADING_API_QUEUE = "ADD_LOADING_API_QUEUE";
export const DEL_LOADING_API_QUEUE = "DEL_LOADING_API_QUEUE";

export const SET_BREADCRUMB = "SET_BREADCRUMB";
export const CLEAR_BREADCRUMB = "CLEAR_BREADCRUMB";

export const SET_POSTS = "SET_POSTS";
