export const SET_USER_INFO = "SET_USER_INFO";
export const CLEAR_USER_INFO = "CLEAR_USER_INFO";

export const ADD_LOADING_API_QUEUE = "ADD_LOADING_API_QUEUE";
export const DEL_LOADING_API_QUEUE = "DEL_LOADING_API_QUEUE";
export const CLEAR_LOADING_API_QUEUE = "CLEAR_LOADING_API_QUEUE";
